import type { Student } from "./types.ts";

// Generates a personalized Gemini-based sales bot for the student.
// This bot handles their own leads — collecting info, following up, closing sales.
// It uses Gemini API (which the student already has) instead of Claude.
export function generateStudentBotCode(student: Student): string {
  const firstName = (student.full_name ?? "").split(" ")[0] || "EEM26";
  const botName = `${firstName} EEM26 Assistant`;
  const adminId = student.telegram_chat_id;
  const salesPageLink = student.sales_page_link ?? "https://payhip.com";
  const premiumPageLink = student.github_repo_premium ?? salesPageLink;
  const payhipLink = student.payhip_link ?? "https://payhip.com";

  return `// ============================================================
// ${botName} — EEM26 Sales Bot
// Generated by Amara | Your personal AI sales assistant
// Powered by Google Gemini
// ============================================================

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const BOT_TOKEN = Deno.env.get("BOT_TOKEN")!;
const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY")!;
const ADMIN_CHAT_ID = "${adminId}";
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
const GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent";
const TG_BASE = \`https://api.telegram.org/bot\${BOT_TOKEN}\`;

const SALES_PAGE = "${salesPageLink}";
const PREMIUM_PAGE = "${premiumPageLink}";
const PAYHIP_LINK = "${payhipLink}";
const PURCHASE_PRICE = 39820;

const SYSTEM_PROMPT = \`You are a warm, confident and conversational sales assistant for EEM26. Your name is Alex.
You NEVER reveal you are an AI. Maximum 2-3 sentences per message. Write like you're texting a friend.

ABOUT EEM26:
EEM26 is a complete done-with-you digital business model. Students get AI tools, premium software, and 4 personal coaches for 4 days.

THE 2 SYSTEMS:
- AAM (Automate and Attract Method): brings buyers to DMs automatically, no ads needed
- SRE (Smart Reply Engine): AI that handles replies and closes sales on autopilot

THE 4-DAY SETUP:
Day 1: SRE + AAM configured — AI starts working from day one
Day 2: Full integration and tools setup — coaches handle everything
Day 3: Sales page goes live — professional, built to convert
Day 4: Coach Victor personally handles final setup — student starts earning SAME DAY. Only 5 people per batch.

REAL STUDENT RESULTS:
- Harry Obilonu (Nigeria): ₦264,560 + GH₵330 + CFA 17,869
- Excel Stanley (Nigeria): ₦373,115 + GH₵378 + CFA 20,118
- Ahmad Nasir (Kaduna): ₦359,400 in affiliate earnings, 20 sales
- As Digitals (Ghana): ₦344,430 + CFA 17,672

LINKS:
- Sales page: \${SALES_PAGE}
- Premium page: \${PREMIUM_PAGE}
- Payhip store: \${PAYHIP_LINK}

STAGES:
Stage 1 (NEW): Collect name, country, struggle, email. Ask all 3 together in first message. Once confirmed output DATA line.
Stage 2 (ATTENDED): CLOSE the sale. Reference Sunday training. Push premium link. Handle objections confidently.
Stage 3 (PURCHASED): Celebrate. Walk through 4-day setup. Build excitement.

DATA OUTPUT: When all 4 details confirmed, output at end of message (invisible to user):
DATA:name=X,country=X,pain_point=X,email=X

SIGNALS (always output, invisible to user):
INTEREST:hot/warm/cold
OBJECTION:brief description or none
HOT_LEAD (only when clearly about to buy)\`;

async function gemini(history: Array<{role: string; message: string}>, userMsg: string, ctx?: string): Promise<string> {
  const systemText = ctx ? SYSTEM_PROMPT + "\\n\\n" + ctx : SYSTEM_PROMPT;
  const contents = history.slice(-10).map(h => ({
    role: h.role === "user" ? "user" : "model",
    parts: [{ text: h.message }]
  }));
  contents.push({ role: "user", parts: [{ text: userMsg }] });

  const res = await fetch(\`\${GEMINI_URL}?key=\${GEMINI_API_KEY}\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: systemText }] },
      contents,
      generationConfig: { temperature: 0.9, maxOutputTokens: 400, topP: 0.95 }
    })
  });
  const data = await res.json();
  return data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ?? "Be right back! 😊";
}

async function tg(method: string, body: Record<string, unknown>): Promise<void> {
  await fetch(\`\${TG_BASE}/\${method}\`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body)
  });
}

function clean(text: string): string {
  return text
    .replace(/DATA:[^\\n]*/g, "")
    .replace(/INTEREST:[^\\n]*/g, "")
    .replace(/OBJECTION:[^\\n]*/g, "")
    .replace(/HOT_LEAD\\n?/gi, "")
    .replace(/\\*\\*([^*]+)\\*\\*/g, "$1")
    .trim();
}

Deno.serve(async (req: Request): Promise<Response> => {
  if (req.method !== "POST") return new Response("ok");
  try {
    const update = await req.json();
    const msg = update?.message;
    if (!msg?.text && !msg?.photo) return new Response("ok");

    const chatId = String(msg.chat.id);
    const userText = (msg.text || "").trim();

    // Photo handler — payment screenshot
    if (msg.photo) {
      const { data: lead } = await sb.from("leads").select("*").eq("telegram_chat_id", chatId).single();
      if (lead?.purchase_screenshot_requested) {
        const photo = msg.photo[msg.photo.length - 1];
        const fileRes = await fetch(\`\${TG_BASE}/getFile?file_id=\${photo.file_id}\`);
        const fileData = await fileRes.json();
        const filePath = fileData.result?.file_path;
        if (filePath) {
          const imgRes = await fetch(\`https://api.telegram.org/file/bot\${BOT_TOKEN}/\${filePath}\`);
          const imgBuf = await imgRes.arrayBuffer();
          const b64 = btoa(String.fromCharCode(...new Uint8Array(imgBuf).subarray(0, 2000)));
          // Simple check — just confirm and mark purchased
          await sb.from("leads").update({ status: "PURCHASED", purchase_screenshot_requested: false }).eq("id", lead.id);
          await tg("sendMessage", { chat_id: chatId, text: "Payment confirmed! ✅ Welcome to EEM26! Your 4-day setup begins. The coaches will reach you shortly. 🔥" });
          await tg("sendMessage", { chat_id: ADMIN_CHAT_ID, text: \`💰 PURCHASE CONFIRMED\\n\\nName: \${lead.name}\\nCountry: \${lead.country}\\nEmail: \${lead.email}\\nBegin 4-day setup.\` });
          void b64;
        }
      }
      return new Response("ok");
    }

    if (!userText) return new Response("ok");

    let { data: lead } = await sb.from("leads").select("*").eq("telegram_chat_id", chatId).single();
    if (!lead) {
      const { data } = await sb.from("leads").insert({ telegram_chat_id: chatId, status: "NEW" }).select().single();
      lead = data;
    }

    const { data: history } = await sb.from("conversations")
      .select("role, message")
      .eq("lead_id", lead.id)
      .order("created_at", { ascending: true })
      .limit(14);

    const leadCtx = \`Lead: \${lead.name || "unknown"} | Country: \${lead.country || "unknown"} | Status: \${lead.status} | Data collected: \${lead.data_collected ? "YES" : "NO"}\`;
    const rawReply = await gemini(history || [], userText, leadCtx);

    const dataMatch = rawReply.match(/DATA:name=([^,\\n]+),country=([^,\\n]+),pain_point=([^,\\n]+),email=([^\\n]+)/i);
    if (dataMatch && !lead.data_collected) {
      await sb.from("leads").update({
        name: dataMatch[1].trim(), country: dataMatch[2].trim(),
        pain_point: dataMatch[3].trim(), email: dataMatch[4].trim(),
        status: "REGISTERED", data_collected: true
      }).eq("id", lead.id);
    }

    const purchaseWords = ["downloaded", "i downloaded", "i bought", "i paid", "i purchased"];
    if (purchaseWords.some(w => userText.toLowerCase().includes(w)) && lead.status === "ATTENDED") {
      await sb.from("leads").update({ purchase_screenshot_requested: true }).eq("id", lead.id);
    }

    if (/HOT_LEAD/i.test(rawReply)) {
      await tg("sendMessage", { chat_id: ADMIN_CHAT_ID, text: \`🔥 HOT LEAD\\n\${lead.name || "Unknown"} (\${lead.country || "?"}) just said: "\${userText}"\` });
    }

    const reply = clean(rawReply);
    await sb.from("conversations").insert([
      { lead_id: lead.id, role: "user", message: userText },
      { lead_id: lead.id, role: "assistant", message: reply }
    ]);
    await tg("sendMessage", { chat_id: chatId, text: reply });
    await sb.from("leads").update({ last_contacted_at: new Date().toISOString() }).eq("id", lead.id);

  } catch (e) {
    console.error("Bot error:", e);
  }
  return new Response("ok");
});
`;
}

// SQL to run in student's Supabase to create their bot tables
export const STUDENT_BOT_SQL = `
-- Leads table for your EEM26 sales bot
CREATE TABLE IF NOT EXISTS public.leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  telegram_chat_id TEXT UNIQUE NOT NULL,
  name TEXT,
  country TEXT,
  pain_point TEXT,
  email TEXT,
  status TEXT NOT NULL DEFAULT 'NEW',
  data_collected BOOLEAN NOT NULL DEFAULT FALSE,
  interest_level TEXT,
  objections_raised TEXT,
  purchase_screenshot_requested BOOLEAN NOT NULL DEFAULT FALSE,
  last_contacted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Conversations table
CREATE TABLE IF NOT EXISTS public.conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id UUID NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_leads_chat ON public.leads(telegram_chat_id);
CREATE INDEX IF NOT EXISTS idx_convs_lead ON public.conversations(lead_id, created_at DESC);

-- RLS
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon all on leads" ON public.leads FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "anon all on conversations" ON public.conversations FOR ALL TO anon USING (true) WITH CHECK (true);

SELECT 'Tables created successfully!' as result;
`;
